### ISSUE TITLE
Artefacts at 1850-07-04?

### ISSUE THREAD

**Issue by hadley** [ropensci/USAboundaries#9]
```R
library(USAboundaries)
map <- us_boundaries("1850-07-04")
library(sp)
plot(map)
````
![screen shot 2015-06-16 at 10 43 09 am](https://cloud.githubusercontent.com/assets/4196/8187256/7e4d28b6-1414-11e5-900d-39cd8297bac2.png)

**Comment by lmullen** [comment]
Those boundaries are correct. The West in 1850 was complicated, because Texas had recently been annexed as a state after its short history as an independent republic, because Mexico had ceded territory to the United States in 1848 after the Mexican War, and because of land claims in Oregon Territory. But the reason for the overlap in this map is the [State of Deseret](https://en.wikipedia.org/wiki/State_of_Deseret). Mormons had migrated to the Great Basin, and functioned as a semi-independent state for a number of years, including their own proposed borders. Things didn't really stabilize in Utah Territory until the Civil War, when the federal government had to make some concessions to keep Mormons quiet. 

You'll get a map without overlap if you filter out Deseret.

```
filter <- map@data$id != "ds_deseret"
plot(map[filter, ])
```

![rplot](https://cloud.githubusercontent.com/assets/183672/8188171/20828862-1422-11e5-8070-a83c8a5baa5c.png)

**Comment by hadley** [comment]
Cool, thanks for the explanation!
